import PayPalIpn, {TransactionType} from "./index";

const myIpn: PayPalIpn = {
    transaction_subject: '',
    payment_date: '',
    txn_type: 'web_accept',
    last_name: 'Doe',
    first_name: 'John',
    residence_country: 'US',
    item_name: 'test',
    mc_currency: 'USD',
    business: 'business@example.com',
    payment_type: 'instant',
    protection_eligibility: 'Eligible',
    verify_sign: 'some-hash',
    payer_status: 'verified',
    payer_email: 'john-doe@example.com',
    txn_id: '9HS820472B17626SJ',
    quantity: '1',
    receiver_email: 'business.accounting@example.com',
    invoice: 'E-00000001',
    payer_id: 'CXEJQBQQ3E9L',
    receiver_id: 'XH1CFXOTVYJLS',
    item_number: 'some-item-identifier',
    payment_status: 'Completed',
    mc_fee: '0.32',
    mc_gross:'0.50',
    custom: '',
    charset: 'windows-1252',
    notify_version: '3.9',
    ipn_track_id: 'fbafaojtyw23',
    cmd: "_notify-validate",
};